name: 'deploy to s3'
description: 'deploy html to s3 bucket'
inputs:
  bucket:
    description: 'bucket name'
    required: true
  region:
    description: 'bucket region'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'folder'
    required: true
runs:
  using: 'node20'
  main: 'main.js'
